package org.myshelfie.network.messages.gameMessages;

/**
 * Empty interface that will be implemented by all the possible enum
 * that collects different classes of events generated by server-side components.
 */
public interface ServerEvent {
}
