name: Codecov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs: 
  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
